// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.WebMVC.Migrations.Migrations
{
    [DbContext(typeof(BookHubDbContext))]
    [Migration("20251201191805_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Emerald",
                            Surname = "Senger"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Robbie",
                            Surname = "Wilderman"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dax",
                            Surname = "MacGyver"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hortense",
                            Surname = "Romaguera"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gudrun",
                            Surname = "Mann"
                        });
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EditCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastEditedById")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LastEditedById");

                    b.HasIndex("PublisherId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 3,
                            Description = "Porro enim suscipit sed. Soluta maxime et quo tempora. Ipsum corrupti et ad qui deserunt in et praesentium ut. Ipsa doloremque voluptatem libero hic doloribus rerum iste atque. Et omnis delectus.",
                            EditCount = 1,
                            ISBN = "0911314746372",
                            LastEditedById = 3,
                            Price = 19.15m,
                            PublisherId = 1,
                            Title = "Corporis iure voluptatem eum sed veniam."
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Description = "Labore et voluptatum itaque libero alias qui ullam eveniet. Laudantium voluptatem et et sed. Autem dolor repellendus rerum non distinctio voluptatem est cum adipisci.",
                            EditCount = 0,
                            ISBN = "7433615861507",
                            LastEditedById = 2,
                            Price = 18.49m,
                            PublisherId = 3,
                            Title = "Quas veniam aspernatur ut."
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Description = "Rem saepe iure adipisci eligendi error. Ut quo repellendus voluptas necessitatibus et ut sapiente. Ut ea consequatur.",
                            EditCount = 1,
                            ISBN = "4789258920051",
                            LastEditedById = 1,
                            Price = 9.92m,
                            PublisherId = 4,
                            Title = "Eos architecto id iste maiores error."
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Description = "Dolorem dolore architecto magni quibusdam temporibus. Quod laboriosam excepturi. Enim et corrupti accusamus maiores velit et. Voluptatum saepe quod minus repellendus placeat quia id eveniet velit. Fugit optio provident. Ipsam fugit et repudiandae natus quos accusantium ducimus.",
                            EditCount = 5,
                            ISBN = "5652596082882",
                            LastEditedById = 1,
                            Price = 16.14m,
                            PublisherId = 4,
                            Title = "Sint iusto dolorem architecto dolorem placeat."
                        });
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookReview");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Cupiditate rem quas minima ipsa impedit quia voluptas quos nam.",
                            BookId = 3,
                            Stars = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Body = "Et neque omnis eveniet error enim inventore et veniam.",
                            BookId = 2,
                            Stars = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Body = "Qui facere optio ullam qui alias doloremque quos facilis officia.",
                            BookId = 1,
                            Stars = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Body = "Tempora ut architecto id fugiat qui et deserunt ut.",
                            BookId = 1,
                            Stars = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Body = "Maiores deleniti consequatur in soluta debitis cumque voluptatem.",
                            BookId = 4,
                            Stars = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            Body = "Autem ea excepturi ipsum ducimus perspiciatis est autem.",
                            BookId = 4,
                            Stars = 2,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 4,
                            Quantity = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            Quantity = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Quantity = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 3,
                            Quantity = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("DAL.Models.GenreBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("BookId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("GenreBooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            GenreId = 2,
                            IsPrimary = true
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            GenreId = 5,
                            IsPrimary = false
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            GenreId = 4,
                            IsPrimary = false
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            GenreId = 6,
                            IsPrimary = false
                        },
                        new
                        {
                            Id = 5,
                            BookId = 2,
                            GenreId = 5,
                            IsPrimary = true
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            GenreId = 1,
                            IsPrimary = false
                        },
                        new
                        {
                            Id = 7,
                            BookId = 3,
                            GenreId = 4,
                            IsPrimary = true
                        },
                        new
                        {
                            Id = 8,
                            BookId = 3,
                            GenreId = 5,
                            IsPrimary = false
                        },
                        new
                        {
                            Id = 9,
                            BookId = 4,
                            GenreId = 8,
                            IsPrimary = false
                        },
                        new
                        {
                            Id = 10,
                            BookId = 4,
                            GenreId = 1,
                            IsPrimary = true
                        });
                });

            modelBuilder.Entity("DAL.Models.Giftcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Giftcard");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 250m,
                            Name = "Gorgeous Steel Keyboard",
                            ValidFrom = new DateTime(2023, 6, 18, 19, 1, 12, 14, DateTimeKind.Unspecified).AddTicks(4114),
                            ValidTo = new DateTime(2024, 10, 18, 19, 1, 12, 14, DateTimeKind.Unspecified).AddTicks(4114)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2000m,
                            Name = "Tasty Soft Keyboard",
                            ValidFrom = new DateTime(2023, 11, 24, 23, 38, 44, 729, DateTimeKind.Unspecified).AddTicks(9821),
                            ValidTo = new DateTime(2025, 5, 24, 23, 38, 44, 729, DateTimeKind.Unspecified).AddTicks(9821)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 500m,
                            Name = "Fantastic Granite Pants",
                            ValidFrom = new DateTime(2023, 6, 23, 6, 31, 49, 17, DateTimeKind.Unspecified).AddTicks(5070),
                            ValidTo = new DateTime(2024, 11, 23, 6, 31, 49, 17, DateTimeKind.Unspecified).AddTicks(5070)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 500m,
                            Name = "Small Frozen Keyboard",
                            ValidFrom = new DateTime(2024, 4, 3, 15, 8, 13, 910, DateTimeKind.Unspecified).AddTicks(6024),
                            ValidTo = new DateTime(2025, 2, 3, 15, 8, 13, 910, DateTimeKind.Unspecified).AddTicks(6024)
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2000m,
                            Name = "Awesome Plastic Fish",
                            ValidFrom = new DateTime(2024, 2, 19, 12, 42, 4, 797, DateTimeKind.Unspecified).AddTicks(105),
                            ValidTo = new DateTime(2024, 8, 19, 12, 42, 4, 797, DateTimeKind.Unspecified).AddTicks(105)
                        });
                });

            modelBuilder.Entity("DAL.Models.GiftcardCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GiftcardId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GiftcardId");

                    b.HasIndex("OrderId");

                    b.ToTable("GiftcardCode");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GC-2067-0459",
                            GiftcardId = 1,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "GC-9162-0020",
                            GiftcardId = 1,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "GC-2242-2861",
                            GiftcardId = 1,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 4,
                            Code = "GC-0963-1222",
                            GiftcardId = 1,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 5,
                            Code = "GC-1303-4709",
                            GiftcardId = 1,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 6,
                            Code = "GC-9585-6193",
                            GiftcardId = 1,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 7,
                            Code = "GC-1645-7220",
                            GiftcardId = 1,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 8,
                            Code = "GC-7982-8168",
                            GiftcardId = 1,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 9,
                            Code = "GC-5950-4042",
                            GiftcardId = 1,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 10,
                            Code = "GC-0063-4668",
                            GiftcardId = 1,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 11,
                            Code = "GC-9356-3928",
                            GiftcardId = 2,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 12,
                            Code = "GC-2280-5483",
                            GiftcardId = 2,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 13,
                            Code = "GC-3324-7884",
                            GiftcardId = 2,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 14,
                            Code = "GC-4188-7925",
                            GiftcardId = 2,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 15,
                            Code = "GC-1714-6469",
                            GiftcardId = 2,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 16,
                            Code = "GC-1181-8289",
                            GiftcardId = 2,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 17,
                            Code = "GC-5545-6429",
                            GiftcardId = 2,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 18,
                            Code = "GC-6972-5613",
                            GiftcardId = 2,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 19,
                            Code = "GC-4412-4721",
                            GiftcardId = 2,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 20,
                            Code = "GC-2351-2467",
                            GiftcardId = 2,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 21,
                            Code = "GC-4752-0825",
                            GiftcardId = 3,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 22,
                            Code = "GC-6707-3359",
                            GiftcardId = 3,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 23,
                            Code = "GC-8384-2395",
                            GiftcardId = 3,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 24,
                            Code = "GC-2903-0306",
                            GiftcardId = 3,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 25,
                            Code = "GC-6055-3573",
                            GiftcardId = 3,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 26,
                            Code = "GC-8162-4513",
                            GiftcardId = 3,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 27,
                            Code = "GC-7595-4089",
                            GiftcardId = 3,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 28,
                            Code = "GC-0114-7627",
                            GiftcardId = 3,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 29,
                            Code = "GC-4438-7079",
                            GiftcardId = 3,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 30,
                            Code = "GC-0044-5440",
                            GiftcardId = 3,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 31,
                            Code = "GC-0596-2995",
                            GiftcardId = 4,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 32,
                            Code = "GC-7734-5939",
                            GiftcardId = 4,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 33,
                            Code = "GC-1025-8845",
                            GiftcardId = 4,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 34,
                            Code = "GC-5326-1317",
                            GiftcardId = 4,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 35,
                            Code = "GC-7444-9232",
                            GiftcardId = 4,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 36,
                            Code = "GC-0959-9803",
                            GiftcardId = 4,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 37,
                            Code = "GC-0986-5730",
                            GiftcardId = 4,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 38,
                            Code = "GC-7604-0899",
                            GiftcardId = 4,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 39,
                            Code = "GC-7143-9475",
                            GiftcardId = 4,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 40,
                            Code = "GC-4506-8477",
                            GiftcardId = 4,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 41,
                            Code = "GC-7500-8996",
                            GiftcardId = 5,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 42,
                            Code = "GC-6251-9180",
                            GiftcardId = 5,
                            IsUsed = true
                        },
                        new
                        {
                            Id = 43,
                            Code = "GC-0490-3319",
                            GiftcardId = 5,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 44,
                            Code = "GC-8727-2649",
                            GiftcardId = 5,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 45,
                            Code = "GC-4655-6927",
                            GiftcardId = 5,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 46,
                            Code = "GC-8245-5832",
                            GiftcardId = 5,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 47,
                            Code = "GC-1040-8942",
                            GiftcardId = 5,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 48,
                            Code = "GC-6635-3263",
                            GiftcardId = 5,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 49,
                            Code = "GC-4682-5804",
                            GiftcardId = 5,
                            IsUsed = false
                        },
                        new
                        {
                            Id = 50,
                            Code = "GC-6301-7067",
                            GiftcardId = 5,
                            IsUsed = false
                        });
                });

            modelBuilder.Entity("DAL.Models.LocalIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GiftcardCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GiftcardCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2018, 5, 5, 23, 25, 15, 929, DateTimeKind.Unspecified).AddTicks(1720),
                            PaymentStatus = 0,
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 5, 5, 0, 59, 57, 630, DateTimeKind.Unspecified).AddTicks(9772),
                            PaymentStatus = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 10, 7, 14, 33, 12, 198, DateTimeKind.Unspecified).AddTicks(2334),
                            PaymentStatus = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 10, 30, 18, 29, 8, 107, DateTimeKind.Unspecified).AddTicks(8890),
                            PaymentStatus = 0,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 2,
                            OrderId = 1,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            OrderId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            OrderId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            BookId = 1,
                            OrderId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            BookId = 3,
                            OrderId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 6,
                            BookId = 4,
                            OrderId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 7,
                            BookId = 1,
                            OrderId = 3,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 8,
                            BookId = 2,
                            OrderId = 3,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 9,
                            BookId = 1,
                            OrderId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 10,
                            BookId = 2,
                            OrderId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 11,
                            BookId = 1,
                            OrderId = 4,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 12,
                            BookId = 3,
                            OrderId = 4,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Grady - Reilly"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Auer, Wilderman and Cormier"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Howe Group"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shields LLC"
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Halle_Lehner63@hotmail.com",
                            IsBanned = false,
                            Username = "Gage.VonRueden96"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Paul_Gorczany@hotmail.com",
                            IsBanned = false,
                            Username = "Guadalupe31"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Icie_Rutherford43@hotmail.com",
                            IsBanned = false,
                            Username = "Deion.Bashirian"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Marlon68@yahoo.com",
                            IsBanned = false,
                            Username = "Natasha77"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Leonardo65@yahoo.com",
                            IsBanned = false,
                            Username = "Gretchen_Dare"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Fannie.Lakin9@hotmail.com",
                            IsBanned = false,
                            Username = "Eulah47"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Mohammed.Gerhold99@yahoo.com",
                            IsBanned = false,
                            Username = "Destini.Pfannerstill"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Erik.Bailey@hotmail.com",
                            IsBanned = false,
                            Username = "Trenton.Schaefer51"
                        });
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.HasOne("DAL.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "LastEditedBy")
                        .WithMany()
                        .HasForeignKey("LastEditedById");

                    b.HasOne("DAL.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("LastEditedBy");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Cart")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.GenreBook", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany("Genres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("DAL.Models.GiftcardCode", b =>
                {
                    b.HasOne("DAL.Models.Giftcard", "Giftcard")
                        .WithMany("Codes")
                        .HasForeignKey("GiftcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Giftcard");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.LocalIdentityUser", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.HasOne("DAL.Models.GiftcardCode", "GiftcardCode")
                        .WithMany()
                        .HasForeignKey("GiftcardCodeId");

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiftcardCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Models.LocalIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Models.LocalIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.LocalIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Models.LocalIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.Giftcard", b =>
                {
                    b.Navigation("Codes");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
