// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.WebAPI.Migrations.Migrations
{
    [DbContext(typeof(BookHubDbContext))]
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
    [Migration("20251114124303_remigrated")]
    partial class remigrated
========
    [Migration("20251030170836_migrated_migration")]
    partial class migrated_migration
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            GenresId = 1
                        },
                        new
                        {
                            BooksId = 1,
                            GenresId = 4
                        },
                        new
                        {
                            BooksId = 2,
                            GenresId = 2
                        },
                        new
                        {
                            BooksId = 3,
                            GenresId = 3
                        },
                        new
                        {
                            BooksId = 4,
                            GenresId = 5
                        });
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Name = "Earnest",
                            Surname = "Metz"
========
                            Name = "Ettie",
                            Surname = "Ankunding"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Name = "Adrian",
                            Surname = "Willms"
========
                            Name = "Abdiel",
                            Surname = "Crist"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Name = "Mara",
                            Surname = "Quigley"
========
                            Name = "Octavia",
                            Surname = "Bode"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Name = "Ansel",
                            Surname = "Haley"
========
                            Name = "Nikko",
                            Surname = "Lebsack"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 5,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Name = "Duane",
                            Surname = "Nienow"
========
                            Name = "Adalberto",
                            Surname = "MacGyver"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EditCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastEditedById")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LastEditedById");

                    b.HasIndex("PublisherId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            AuthorId = 5,
                            Description = "Sed suscipit est ea consequuntur ducimus et culpa. Laudantium perspiciatis placeat. Nostrum officiis quia distinctio doloremque modi.",
                            EditCount = 3,
                            ISBN = "6047833501377",
                            LastEditedById = 2,
                            Price = 5.20m,
                            PublisherId = 2,
                            Title = "Saepe ut iusto fugit aliquam."
========
                            AuthorId = 1,
                            Description = "Eos eius eligendi natus nemo. Vitae quis possimus incidunt. Vel vel sint. Libero ea nihil eum at eum cumque facilis ut. Totam facere deleniti et.",
                            ISBN = "9613120562412",
                            Price = 16.05m,
                            PublisherId = 3,
                            Title = "Qui vel nesciunt nam voluptatem."
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            AuthorId = 1,
                            Description = "Deserunt doloribus voluptates est deleniti in deserunt maiores. Et autem at ratione. Excepturi pariatur architecto ea. Provident magnam alias ad facilis. Ex dignissimos suscipit voluptatem aut dolor quidem nihil doloribus quos.",
                            EditCount = 10,
                            ISBN = "3519362025622",
                            LastEditedById = 5,
                            Price = 11.13m,
                            PublisherId = 1,
                            Title = "Omnis quaerat quaerat labore sit."
========
                            AuthorId = 2,
                            Description = "Quam voluptatibus nostrum rerum ab et aut. Aut libero voluptatem deserunt. Laborum possimus ut aut libero voluptas quisquam totam quis.",
                            ISBN = "9968367676430",
                            Price = 12.03m,
                            PublisherId = 4,
                            Title = "Assumenda dolorum distinctio et."
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            AuthorId = 4,
                            Description = "Incidunt adipisci mollitia delectus. Reprehenderit nobis hic et. Qui exercitationem quae nihil quod porro corporis repellendus. Asperiores itaque iusto velit amet molestiae consequuntur dolores nulla.",
                            EditCount = 4,
                            ISBN = "8288025698118",
                            LastEditedById = 2,
                            Price = 18.38m,
                            PublisherId = 1,
                            Title = "Hic et eius iste eos."
========
                            AuthorId = 2,
                            Description = "Totam voluptatem iste. Beatae iusto dolor saepe et enim. Dolor rerum qui minus quia.",
                            ISBN = "3068705779239",
                            Price = 17.73m,
                            PublisherId = 1,
                            Title = "Voluptatum vel saepe architecto perferendis enim."
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            AuthorId = 3,
                            Description = "Voluptate fugiat pariatur neque quis non. Ipsa iste eaque sed reiciendis quibusdam nulla aperiam. Asperiores error quasi doloremque sed dolorem. Mollitia ipsa sunt. Vel consectetur provident aut sunt officia soluta iure.",
                            EditCount = 7,
                            ISBN = "8678088193635",
                            LastEditedById = 3,
                            Price = 9.73m,
                            PublisherId = 2,
                            Title = "Dolorem laboriosam tenetur provident et."
========
                            AuthorId = 5,
                            Description = "Consequuntur autem perspiciatis quo et odit iste quisquam ut. Et aspernatur ut enim est delectus sunt. Fugit quo et rerum et ducimus adipisci eveniet. Omnis explicabo pariatur aut magni nihil hic quae maxime quod.",
                            ISBN = "4333767004315",
                            Price = 15.14m,
                            PublisherId = 1,
                            Title = "Quo nisi deserunt dolorem voluptatibus repellat."
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookReview");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Body = "Et consequatur id nisi et ipsum omnis ut.",
                            BookId = 4,
                            Stars = 4,
                            UserId = 2
========
                            Body = "Eos atque possimus ipsum enim eius ipsam nostrum pariatur.",
                            BookId = 3,
                            Stars = 4,
                            UserId = 5
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Body = "Ex ratione velit consequatur earum optio doloribus sit similique.",
                            BookId = 3,
                            Stars = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            Body = "Qui asperiores eos nemo ab quo ut iusto beatae eos.",
                            BookId = 2,
                            Stars = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Body = "Rerum voluptatum vel deleniti consectetur assumenda eaque exercitationem tenetur.",
                            BookId = 2,
                            Stars = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            Body = "Quis quidem ut velit dignissimos maiores inventore consequatur voluptatibus suscipit.",
                            BookId = 1,
                            Stars = 3,
========
                            Body = "Quas occaecati qui quod dolor quia magnam doloremque.",
                            BookId = 3,
                            Stars = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 3,
                            Body = "Reprehenderit quod doloremque est et quia est natus nobis et.",
                            BookId = 4,
                            Stars = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Body = "Illo quia suscipit totam accusantium doloribus qui nam sed ullam.",
                            BookId = 4,
                            Stars = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            Body = "Qui incidunt amet excepturi impedit mollitia repellendus dolores aliquid.",
                            BookId = 3,
                            Stars = 1,
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                            UserId = 8
                        },
                        new
                        {
                            Id = 6,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Body = "Autem fuga officia eveniet neque perspiciatis maxime consequuntur libero soluta.",
                            BookId = 2,
                            Stars = 2,
                            UserId = 7
========
                            Body = "Incidunt neque natus deserunt quae totam minus quibusdam et accusantium.",
                            BookId = 2,
                            Stars = 3,
                            UserId = 2
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            BookId = 2,
                            Quantity = 3,
                            UserId = 3
========
                            BookId = 1,
                            Quantity = 4,
                            UserId = 1
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 2,
                            BookId = 4,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Quantity = 3,
                            UserId = 7
========
                            Quantity = 2,
                            UserId = 8
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            BookId = 4,
                            Quantity = 2,
                            UserId = 6
========
                            BookId = 1,
                            Quantity = 1,
                            UserId = 4
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            BookId = 2,
                            Quantity = 3,
                            UserId = 6
========
                            BookId = 3,
                            Quantity = 4,
                            UserId = 4
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Date = new DateTime(2016, 6, 30, 11, 6, 21, 639, DateTimeKind.Unspecified).AddTicks(7192),
========
                            Date = new DateTime(2023, 7, 4, 22, 36, 55, 849, DateTimeKind.Unspecified).AddTicks(1614),
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Date = new DateTime(2019, 1, 24, 1, 12, 43, 650, DateTimeKind.Unspecified).AddTicks(715),
                            UserId = 3
========
                            Date = new DateTime(2019, 10, 28, 13, 44, 52, 242, DateTimeKind.Unspecified).AddTicks(9150),
                            UserId = 7
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Date = new DateTime(2019, 7, 19, 15, 12, 51, 716, DateTimeKind.Unspecified).AddTicks(4196),
                            UserId = 4
========
                            Date = new DateTime(2022, 3, 23, 11, 44, 55, 630, DateTimeKind.Unspecified).AddTicks(1992),
                            UserId = 5
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Date = new DateTime(2023, 8, 16, 0, 8, 43, 387, DateTimeKind.Unspecified).AddTicks(6816),
                            UserId = 1
========
                            Date = new DateTime(2019, 4, 14, 8, 48, 16, 281, DateTimeKind.Unspecified).AddTicks(9041),
                            UserId = 7
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 2,
                            OrderId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            OrderId = 1,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Quantity = 2
========
                            Quantity = 1
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            BookId = 4,
                            OrderId = 1,
                            Quantity = 3
========
                            BookId = 1,
                            OrderId = 1,
                            Quantity = 5
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 4,
                            BookId = 1,
                            OrderId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            BookId = 1,
                            OrderId = 2,
========
                            BookId = 3,
                            OrderId = 3,
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            BookId = 4,
                            OrderId = 3,
                            Quantity = 1
========
                            BookId = 2,
                            OrderId = 3,
                            Quantity = 2
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 7,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            BookId = 4,
                            OrderId = 3,
                            Quantity = 3
========
                            BookId = 1,
                            OrderId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            BookId = 2,
                            OrderId = 4,
                            Quantity = 5
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 8,
                            BookId = 1,
                            OrderId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            BookId = 3,
                            OrderId = 4,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 10,
                            BookId = 1,
                            OrderId = 4,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Name = "Dietrich, Cormier and Pacocha"
========
                            Name = "Kuhlman and Sons"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Name = "Gibson, Roob and Grady"
========
                            Name = "Kutch, Schmeler and Carroll"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Name = "Gaylord - Bosco"
========
                            Name = "Hammes LLC"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Name = "Cummings, Lubowitz and Kulas"
========
                            Name = "Daugherty - Considine"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Email = "Jayde_Yundt91@hotmail.com",
                            IsBanned = false,
                            Username = "Bernhard_Ratke"
========
                            Email = "Assunta.Reilly7@hotmail.com",
                            IsBanned = false,
                            Username = "Anita61"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Email = "Floyd_Moore@yahoo.com",
                            IsBanned = false,
                            Username = "Molly38"
========
                            Email = "Emory50@hotmail.com",
                            IsBanned = false,
                            Username = "Ruth17"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Email = "Jacky_Weissnat20@gmail.com",
                            IsBanned = false,
                            Username = "Eugene_Marquardt75"
========
                            Email = "Bria_Douglas2@yahoo.com",
                            IsBanned = false,
                            Username = "Darlene.Ruecker20"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Email = "Chauncey.Sipes@gmail.com",
                            IsBanned = false,
                            Username = "Laury.Little"
========
                            Email = "Khalid.Gaylord46@hotmail.com",
                            IsBanned = false,
                            Username = "Fabiola.Robel47"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 5,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Email = "Antonio33@yahoo.com",
                            IsBanned = false,
                            Username = "Kira.McKenzie"
========
                            Email = "Dustin_Gorczany@hotmail.com",
                            IsBanned = false,
                            Username = "Jaeden.Grant87"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 6,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Email = "Leonor12@gmail.com",
                            IsBanned = false,
                            Username = "Vito_Dicki68"
========
                            Email = "Modesto_Friesen@yahoo.com",
                            IsBanned = false,
                            Username = "Jermain81"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 7,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Email = "Dorian8@hotmail.com",
                            IsBanned = false,
                            Username = "Kiel_Smith"
========
                            Email = "Demario.Metz38@gmail.com",
                            IsBanned = false,
                            Username = "Eliseo.Hilpert36"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        },
                        new
                        {
                            Id = 8,
<<<<<<<< HEAD:DAL.WebMVC.Migrations/Migrations/20251114124303_remigrated.Designer.cs
                            Email = "Ford90@hotmail.com",
                            IsBanned = false,
                            Username = "Ramiro64"
========
                            Email = "Claudia_Kutch90@hotmail.com",
                            IsBanned = true,
                            Username = "Gaston1"
>>>>>>>> cd684c3 (seeded Orders to DBs):DAL.WebAPI.Migrations/Migrations/20251030170836_migrated_migration.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItem");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("DAL.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.HasOne("DAL.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "LastEditedBy")
                        .WithMany()
                        .HasForeignKey("LastEditedById");

                    b.HasOne("DAL.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("LastEditedBy");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Cart")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
