// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.WebMVC.Migrations.Migrations
{
    [DbContext(typeof(BookHubDbContext))]
    partial class BookHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            GenresId = 1
                        },
                        new
                        {
                            BooksId = 1,
                            GenresId = 4
                        },
                        new
                        {
                            BooksId = 2,
                            GenresId = 2
                        },
                        new
                        {
                            BooksId = 3,
                            GenresId = 3
                        },
                        new
                        {
                            BooksId = 4,
                            GenresId = 5
                        });
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reba",
                            Surname = "Weber"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mina",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Raegan",
                            Surname = "Cruickshank"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Destini",
                            Surname = "Cummings"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bernhard",
                            Surname = "Ankunding"
                        });
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EditCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastEditedById")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LastEditedById");

                    b.HasIndex("PublisherId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<< HEAD:DAL/Migrations/BookHubDbContextModelSnapshot.cs
                            AuthorId = 4,
                            Description = "In illum aut iste architecto ipsum. Neque quidem est. Quis sunt harum labore quae odit et voluptatem iusto corrupti.",
                            EditCount = 10,
                            ISBN = "1068470320720",
                            LastEditedById = 4,
                            Price = 11.38m,
                            PublisherId = 3,
                            Title = "Culpa velit sapiente quisquam."
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Description = "Nisi nobis ut. Voluptate magnam tempore. Repellendus aliquid quod itaque unde adipisci. Officiis repudiandae dolore qui voluptate ad impedit repudiandae atque.",
                            EditCount = 7,
                            ISBN = "0795729932984",
                            LastEditedById = 3,
                            Price = 14.90m,
                            PublisherId = 2,
                            Title = "Cumque impedit blanditiis error."
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Description = "Veritatis voluptatem magni incidunt quod cumque voluptatem velit distinctio aliquam. Culpa libero sed molestias voluptatem blanditiis ut esse. Perspiciatis earum eos. Nesciunt culpa ut omnis impedit commodi ut. Rerum accusamus ipsum dolorum nisi quibusdam voluptatem hic occaecati ducimus. Porro aspernatur voluptatibus tenetur.",
                            EditCount = 10,
                            ISBN = "7887396245146",
                            LastEditedById = 4,
                            Price = 14.28m,
                            PublisherId = 3,
                            Title = "Laudantium dolor magnam rerum."
                        },
                        new
                        {
                            Id = 4,
<<<<<<< HEAD:DAL/Migrations/BookHubDbContextModelSnapshot.cs
                            AuthorId = 2,
                            Description = "Ipsum est voluptatem est et. Vero ipsum reprehenderit ex inventore corrupti nostrum mollitia in deleniti. Ipsum perferendis magni.",
                            EditCount = 8,
                            ISBN = "4295003193637",
                            LastEditedById = 1,
                            Price = 14.29m,
                            PublisherId = 1,
                            Title = "Consequatur dolorum eos possimus."
                        });
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookReview");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Dolor aliquid id quidem quas aut dolor cumque aut.",
                            BookId = 4,
                            Stars = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Body = "Voluptatem odio nihil dolorem maiores magnam omnis quia commodi.",
                            BookId = 3,
                            Stars = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 3,
                            Body = "Ut esse velit dolores ut non maxime suscipit omnis dolor.",
                            BookId = 4,
                            Stars = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            Body = "Eum et in consectetur fugit ea praesentium debitis.",
                            BookId = 3,
                            Stars = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            Body = "Eligendi quidem eum inventore ratione ratione debitis aut.",
                            BookId = 3,
                            Stars = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Body = "Qui dolor quasi mollitia ea possimus error nesciunt numquam.",
                            BookId = 1,
                            Stars = 3,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Quantity = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
<<<<<<< HEAD:DAL/Migrations/BookHubDbContextModelSnapshot.cs
                            BookId = 1,
                            Quantity = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Quantity = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 4,
                            BookId = 3,
<<<<<<< HEAD:DAL/Migrations/BookHubDbContextModelSnapshot.cs
                            Quantity = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 5, 10, 7, 7, 54, 773, DateTimeKind.Unspecified).AddTicks(1214),
                            UserId = 8
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 5, 26, 15, 56, 29, 908, DateTimeKind.Unspecified).AddTicks(672),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 3, 19, 21, 28, 53, 171, DateTimeKind.Unspecified).AddTicks(2950),
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2016, 9, 25, 9, 57, 29, 631, DateTimeKind.Unspecified).AddTicks(9082),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 3,
                            OrderId = 1,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            OrderId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            BookId = 4,
                            OrderId = 2,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 4,
                            BookId = 1,
                            OrderId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            BookId = 4,
                            OrderId = 3,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            OrderId = 3,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 7,
                            BookId = 2,
                            OrderId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 8,
                            BookId = 3,
                            OrderId = 4,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gerhold, Ruecker and Huel"
=======
                            Name = "Kerluke - Lang"
>>>>>>> 8f98ab0 (separate API and MVC migrations):DAL.WebMVC.Migrations/Migrations/BookHubDbContextModelSnapshot.cs
                        },
                        new
                        {
                            Id = 2,
                            Name = "Swaniawski - Collins"
=======
                            Name = "Dare Group"
>>>>>>> 8f98ab0 (separate API and MVC migrations):DAL.WebMVC.Migrations/Migrations/BookHubDbContextModelSnapshot.cs
                        },
                        new
                        {
                            Id = 3,
                            Name = "Willms, Windler and Lehner"
=======
                            Name = "Bartell Group"
>>>>>>> 8f98ab0 (separate API and MVC migrations):DAL.WebMVC.Migrations/Migrations/BookHubDbContextModelSnapshot.cs
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hegmann LLC"
=======
                            Name = "Klocko, Kerluke and Williamson"
>>>>>>> 8f98ab0 (separate API and MVC migrations):DAL.WebMVC.Migrations/Migrations/BookHubDbContextModelSnapshot.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Fanny.Witting@yahoo.com",
                            IsBanned = false,
                            Username = "Hilma.Pfeffer38"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Justice.Kunde84@hotmail.com",
                            IsBanned = false,
                            Username = "Tevin_Hackett"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Lavada85@yahoo.com",
                            IsBanned = false,
                            Username = "Emory90"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Murphy85@gmail.com",
                            IsBanned = false,
                            Username = "Elisabeth.Powlowski61"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Raleigh56@gmail.com",
                            IsBanned = false,
                            Username = "Alfonso45"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Brant47@hotmail.com",
                            IsBanned = false,
                            Username = "Pauline_Roob"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Lera.Bode@yahoo.com",
                            IsBanned = false,
                            Username = "Jacinto39"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Mitchell44@hotmail.com",
                            IsBanned = false,
                            Username = "Hayley.Walter"
                        });
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItem");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("DAL.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.HasOne("DAL.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "LastEditedBy")
                        .WithMany()
                        .HasForeignKey("LastEditedById");

                    b.HasOne("DAL.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("LastEditedBy");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Cart")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
