// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(BookHubDbContext))]
    [Migration("20251029144523_dbcontext_add_sets_resync")]
    partial class dbcontext_add_sets_resync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            GenresId = 1
                        },
                        new
                        {
                            BooksId = 1,
                            GenresId = 4
                        },
                        new
                        {
                            BooksId = 2,
                            GenresId = 2
                        },
                        new
                        {
                            BooksId = 3,
                            GenresId = 3
                        },
                        new
                        {
                            BooksId = 4,
                            GenresId = 5
                        });
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Florine",
                            Surname = "Keebler"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Robbie",
                            Surname = "Wintheiser"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Adolph",
                            Surname = "Renner"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Juwan",
                            Surname = "Stracke"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Albert",
                            Surname = "Botsford"
                        });
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Aperiam ipsum incidunt ab sit voluptatem quae similique quasi fugiat. Possimus non consequuntur praesentium ratione ipsa necessitatibus voluptas. Maxime sunt optio et officiis quidem natus illum voluptatibus autem. In facilis ducimus quis sint sint exercitationem. Qui occaecati id et. Et et qui ut voluptas.",
                            ISBN = "5809274814505",
                            Price = 18.72m,
                            PublisherId = 3,
                            Title = "Neque repudiandae qui et repellendus."
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 4,
                            Description = "Nostrum non consequuntur officiis rerum consequatur. Necessitatibus et nisi reprehenderit dolorem consequatur dignissimos nisi. Et praesentium maiores nulla molestias nobis autem.",
                            ISBN = "5550707506282",
                            Price = 10.00m,
                            PublisherId = 3,
                            Title = "Harum voluptas assumenda doloribus cupiditate cumque."
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Description = "Beatae molestiae aliquam dicta nostrum amet. Laboriosam rerum dolorem rem eum perspiciatis. Quis enim aut itaque nisi cumque magni. Voluptatibus et eos doloribus quia doloremque reiciendis nihil et rerum. Blanditiis vel impedit explicabo eius. Eum et nisi cumque et.",
                            ISBN = "5565260264364",
                            Price = 17.18m,
                            PublisherId = 2,
                            Title = "Eum qui porro consequuntur aut et."
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Description = "Reiciendis aut distinctio vitae corporis doloremque velit. Aut qui labore sit voluptatem perspiciatis aut. Autem eos eius quod nisi quisquam. Hic reprehenderit labore omnis et distinctio. Voluptates nobis odio qui illo dolorem. Adipisci laboriosam incidunt repellat dolor et.",
                            ISBN = "5579070323456",
                            Price = 6.12m,
                            PublisherId = 2,
                            Title = "Maiores ipsam in hic."
                        });
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookReview");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Et odit blanditiis numquam deserunt quos iusto voluptatum quo.",
                            BookId = 1,
                            Stars = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Body = "Ut quia pariatur natus ab mollitia sunt vitae repellat omnis.",
                            BookId = 2,
                            Stars = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Body = "Dolor ipsam sed et commodi sint odio ratione repellendus.",
                            BookId = 4,
                            Stars = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Body = "Odio vero nobis non maxime expedita numquam eius.",
                            BookId = 4,
                            Stars = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            Body = "Cum excepturi nam similique maxime vel mollitia veritatis.",
                            BookId = 1,
                            Stars = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            Body = "Nam quidem sed natus mollitia quibusdam facere aut.",
                            BookId = 3,
                            Stars = 5,
                            UserId = 8
                        });
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 3,
                            Quantity = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Quantity = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Quantity = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            Quantity = 5,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Waelchi, Hickle and O'Reilly"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wyman, Luettgen and Ernser"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Padberg Inc"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Buckridge, Padberg and Cummerata"
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Chance92@gmail.com",
                            IsBanned = false,
                            Username = "Melany57"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Marc_Reinger91@hotmail.com",
                            IsBanned = false,
                            Username = "Wilfred35"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Jackson.Lemke@hotmail.com",
                            IsBanned = false,
                            Username = "Friedrich_Fahey"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Fletcher85@yahoo.com",
                            IsBanned = false,
                            Username = "Amara1"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Leopoldo_Gulgowski96@gmail.com",
                            IsBanned = false,
                            Username = "Dillon_OKon8"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Isai.Zulauf@hotmail.com",
                            IsBanned = false,
                            Username = "Reyes.Pfannerstill"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Justice_Erdman20@hotmail.com",
                            IsBanned = false,
                            Username = "Philip_MacGyver74"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Keegan35@hotmail.com",
                            IsBanned = false,
                            Username = "Patsy_Kshlerin2"
                        });
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItem");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("DAL.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.HasOne("DAL.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Cart")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
