// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(BookHubDbContext))]
    partial class BookHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            GenresId = 1
                        },
                        new
                        {
                            BooksId = 1,
                            GenresId = 4
                        },
                        new
                        {
                            BooksId = 2,
                            GenresId = 2
                        },
                        new
                        {
                            BooksId = 3,
                            GenresId = 3
                        },
                        new
                        {
                            BooksId = 4,
                            GenresId = 5
                        });
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rosario",
                            Surname = "Sporer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Damaris",
                            Surname = "Haag"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rosalyn",
                            Surname = "Schulist"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shanna",
                            Surname = "Fadel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Woodrow",
                            Surname = "Thompson"
                        });
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Description = "Voluptas cumque quae et ut vel unde. Dolores impedit non deleniti possimus odit illum molestiae ut. Placeat sequi nam magnam velit. Non fugit reiciendis. Officiis dolor cum doloribus nulla eaque inventore sed voluptate et.",
                            ISBN = "1686322064044",
                            Price = 8.32m,
                            PublisherId = 2,
                            Title = "Voluptate voluptas debitis sit."
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Description = "Illum ea blanditiis possimus voluptatibus rerum corrupti temporibus quis. Doloremque sapiente ullam. Voluptate eveniet placeat minus voluptatem voluptas qui ut. Sapiente dolore non dolore a magnam dolore.",
                            ISBN = "0582325371671",
                            Price = 17.15m,
                            PublisherId = 3,
                            Title = "Mollitia atque nobis dolor."
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 5,
                            Description = "Exercitationem eaque autem laudantium. Consequuntur ipsa voluptates natus illo occaecati perferendis molestias placeat. Fuga eius est sequi similique alias quas voluptas aut ut. Recusandae iste neque ab.",
                            ISBN = "4861959228251",
                            Price = 16.26m,
                            PublisherId = 3,
                            Title = "Asperiores dolorum velit explicabo."
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            Description = "Et voluptas asperiores et. Est ut sapiente iure vel perferendis impedit tempore voluptatem. Soluta cupiditate et eos maiores. Quidem optio cum iure dolorem eaque officia quibusdam.",
                            ISBN = "3895470133207",
                            Price = 14.74m,
                            PublisherId = 2,
                            Title = "Tempore facilis sed optio nam."
                        });
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookReview");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Omnis corporis pariatur consequuntur autem asperiores eveniet deserunt facilis.",
                            BookId = 4,
                            Stars = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            Body = "Distinctio vitae voluptates dicta tempora et et mollitia.",
                            BookId = 1,
                            Stars = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Body = "Fugiat dolorum optio maiores sint consequatur commodi quas nostrum velit.",
                            BookId = 3,
                            Stars = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            Body = "Voluptatem iusto eaque beatae commodi excepturi impedit sed.",
                            BookId = 2,
                            Stars = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            Body = "Nam aut veniam odio est quasi est blanditiis quos.",
                            BookId = 2,
                            Stars = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Body = "Quia eveniet quia debitis accusantium nulla officia exercitationem.",
                            BookId = 2,
                            Stars = 3,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Schimmel and Sons"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Green, Zemlak and Bartoletti"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Walsh - Ward"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Auer Inc"
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Edyth70@hotmail.com",
                            IsBanned = true,
                            Username = "Misael.Kuhic94"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Cassandra98@hotmail.com",
                            IsBanned = false,
                            Username = "Cordell.Stamm26"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Fermin_Murazik@hotmail.com",
                            IsBanned = false,
                            Username = "Berta_Ernser69"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Michelle38@hotmail.com",
                            IsBanned = false,
                            Username = "Florencio_King35"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Imani_Smith73@hotmail.com",
                            IsBanned = false,
                            Username = "Velma_Kling60"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Brandyn.Moore@yahoo.com",
                            IsBanned = false,
                            Username = "Lacey.King"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Marcelo52@hotmail.com",
                            IsBanned = false,
                            Username = "Henderson_Bradtke10"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Megane35@yahoo.com",
                            IsBanned = false,
                            Username = "Collin60"
                        });
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItem");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("DAL.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.HasOne("DAL.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
