// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.WebAPI.Migrations.Migrations
{
    [DbContext(typeof(BookHubDbContext))]
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
    [Migration("20251129150137_AddGiftcardCodeToOrder")]
    partial class AddGiftcardCodeToOrder
========
    [Migration("20251129094838_genre_book")]
    partial class genre_book
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Name = "Wilbert",
                            Surname = "Lynch"
========
                            Name = "Dayton",
                            Surname = "Lindgren"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Name = "Fay",
                            Surname = "Crist"
========
                            Name = "Howell",
                            Surname = "Boehm"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Name = "Trevor",
                            Surname = "Metz"
========
                            Name = "Sandy",
                            Surname = "Raynor"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Name = "Griffin",
                            Surname = "Williamson"
========
                            Name = "Sylvester",
                            Surname = "Koelpin"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 5,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Name = "Garrick",
                            Surname = "Collier"
========
                            Name = "Leopold",
                            Surname = "Schmitt"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EditCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastEditedById")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LastEditedById");

                    b.HasIndex("PublisherId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 5,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Description = "Rerum non similique molestias omnis dicta alias nemo fugit. Quia pariatur quos sit. Temporibus quia ducimus est inventore molestias et quisquam commodi. Ut modi hic dicta totam perferendis quasi aut ut repellendus. Ea voluptatem saepe delectus et nemo. Itaque error nihil nihil recusandae quidem facere.",
                            EditCount = 0,
                            ISBN = "7917662334769",
                            LastEditedById = 1,
                            Price = 5.95m,
                            PublisherId = 4,
                            Title = "Vel qui odio iusto."
========
                            Description = "Quibusdam quisquam expedita ea labore repudiandae. Repudiandae quae maxime et et mollitia. Voluptatibus velit sit quis eveniet dolorum modi ratione error voluptatibus.",
                            EditCount = 6,
                            ISBN = "6657637721378",
                            LastEditedById = 3,
                            Price = 17.92m,
                            PublisherId = 4,
                            Title = "Mollitia maiores esse nobis molestiae."
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            AuthorId = 3,
                            Description = "Minus vel repellendus sit velit deleniti aliquam assumenda. Qui enim dolores minus doloribus eos officia non harum voluptatem. Quia numquam consequuntur eos praesentium magni. Est facere aut voluptates voluptatem officiis qui inventore. Consequatur et nesciunt qui sequi ut quia iure quaerat.",
                            EditCount = 3,
                            ISBN = "4895214419023",
                            LastEditedById = 5,
                            Price = 10.11m,
                            PublisherId = 4,
                            Title = "Placeat commodi numquam est harum reprehenderit."
========
                            AuthorId = 5,
                            Description = "Est doloribus omnis odit ut voluptates quia. Optio quo dolor molestiae rem et perferendis et. Rerum quia eligendi blanditiis illum consectetur et. Architecto laboriosam sequi quisquam sit quibusdam.",
                            EditCount = 6,
                            ISBN = "5176980451127",
                            LastEditedById = 3,
                            Price = 15.40m,
                            PublisherId = 4,
                            Title = "Aut fugiat ipsam aperiam."
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            AuthorId = 2,
                            Description = "Non explicabo dolorem quia nam qui omnis. Quia est molestiae assumenda amet sit. Dignissimos exercitationem voluptates dolorem alias voluptates reiciendis sapiente quia aperiam. Et quisquam ut voluptatem ut alias a id corrupti eligendi. Quibusdam vel sunt et mollitia ut sint autem id praesentium. Alias mollitia id qui alias veritatis molestiae ut animi et.",
                            EditCount = 3,
                            ISBN = "1919912237376",
                            LastEditedById = 1,
                            Price = 8.89m,
                            PublisherId = 2,
                            Title = "Error error commodi qui aut."
========
                            AuthorId = 4,
                            Description = "Sint enim atque quo. Consequuntur ea odit corrupti. Blanditiis eius rem accusamus qui nisi qui quidem.",
                            EditCount = 6,
                            ISBN = "5774206508275",
                            LastEditedById = 5,
                            Price = 7.57m,
                            PublisherId = 4,
                            Title = "Aut molestiae deserunt modi molestias facilis."
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Description = "Et mollitia magnam. Molestiae quia repellat porro consequatur sed hic. Aut sit dolorum autem. Mollitia ex maiores sed beatae minus id facilis voluptatem quod.",
                            EditCount = 2,
                            ISBN = "2406227680854",
                            LastEditedById = 4,
                            Price = 14.01m,
                            PublisherId = 2,
                            Title = "Incidunt nihil asperiores delectus sunt debitis."
========
                            Description = "In id exercitationem ducimus ullam. Voluptatem sint porro ullam molestias laudantium. Rerum eum ut excepturi quis id optio. Dolore ea est ea rerum fugit aut atque impedit. Itaque ipsa beatae.",
                            EditCount = 2,
                            ISBN = "1768104718793",
                            LastEditedById = 3,
                            Price = 16.57m,
                            PublisherId = 4,
                            Title = "Aut omnis itaque voluptas porro placeat."
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookReview");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Body = "Doloremque voluptates labore voluptate et blanditiis tempora sed consequatur.",
                            BookId = 2,
                            Stars = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Body = "Aliquid voluptatem labore ab consequatur fugiat sint aut sed.",
                            BookId = 3,
                            Stars = 3,
                            UserId = 2
========
                            Body = "Et sed voluptas id totam excepturi et magni.",
                            BookId = 1,
                            Stars = 4,
                            UserId = 3
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 2,
                            Body = "Debitis omnis iusto quidem eum aut illo culpa delectus quod.",
                            BookId = 3,
                            Stars = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Body = "Porro exercitationem est et nisi suscipit qui quaerat.",
                            BookId = 1,
                            Stars = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Body = "Labore non et aut consequatur sit dolorem commodi quidem.",
                            BookId = 2,
                            Stars = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Body = "Repellat veniam et unde accusamus quasi quasi est doloremque voluptas.",
========
                            Body = "Iste quasi at rerum eum consequatur officiis alias et incidunt.",
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                            BookId = 1,
                            Stars = 3,
                            UserId = 4
                        },
                        new
                        {
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Id = 6,
                            Body = "Mollitia earum deserunt commodi provident est libero autem nobis ipsam.",
                            BookId = 2,
                            Stars = 5,
                            UserId = 2
========
                            Id = 4,
                            Body = "Asperiores pariatur nobis dolores voluptas pariatur consequuntur dolorem incidunt.",
                            BookId = 4,
                            Stars = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            Body = "Inventore sint ducimus odit et eos voluptatibus doloribus officiis.",
                            BookId = 2,
                            Stars = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            Body = "Deleniti nihil velit pariatur harum hic sit dolores et.",
                            BookId = 4,
                            Stars = 1,
                            UserId = 3
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
========
                            BookId = 3,
                            Quantity = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                            BookId = 3,
                            Quantity = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Quantity = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            BookId = 4,
                            Quantity = 3,
                            UserId = 4
========
                            Quantity = 4,
                            UserId = 2
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            BookId = 1,
                            Quantity = 1,
                            UserId = 6
========
                            BookId = 4,
                            Quantity = 1,
                            UserId = 3
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Adventure"
                        });
                });

<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
            modelBuilder.Entity("DAL.Models.Giftcard", b =>
========
            modelBuilder.Entity("DAL.Models.GenreBook", b =>
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Giftcard");
                });

            modelBuilder.Entity("DAL.Models.GiftcardCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GiftcardId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
========
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                    b.HasIndex("GiftcardId");

                    b.HasIndex("OrderId");

                    b.ToTable("GiftcardCode");
========
                    b.HasIndex("GenreId");

                    b.HasIndex("BookId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("GenreBooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            GenreId = 7,
                            IsPrimary = true
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            GenreId = 8,
                            IsPrimary = false
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            GenreId = 6,
                            IsPrimary = false
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            GenreId = 4,
                            IsPrimary = true
                        },
                        new
                        {
                            Id = 5,
                            BookId = 3,
                            GenreId = 7,
                            IsPrimary = false
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            GenreId = 2,
                            IsPrimary = true
                        },
                        new
                        {
                            Id = 7,
                            BookId = 4,
                            GenreId = 7,
                            IsPrimary = true
                        });
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                });

            modelBuilder.Entity("DAL.Models.LocalIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GiftcardCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GiftcardCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Date = new DateTime(2015, 3, 2, 20, 6, 36, 477, DateTimeKind.Unspecified).AddTicks(2626),
========
                            Date = new DateTime(2018, 8, 18, 15, 32, 45, 337, DateTimeKind.Unspecified).AddTicks(7327),
                            PaymentStatus = 0,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 1, 17, 6, 3, 33, 975, DateTimeKind.Unspecified).AddTicks(6926),
                            PaymentStatus = 0,
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 6, 27, 8, 36, 59, 626, DateTimeKind.Unspecified).AddTicks(5734),
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                            PaymentStatus = 0,
                            UserId = 6
                        },
                        new
                        {
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Id = 2,
                            Date = new DateTime(2017, 7, 11, 22, 45, 50, 414, DateTimeKind.Unspecified).AddTicks(7688),
                            PaymentStatus = 0,
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2016, 6, 30, 10, 42, 35, 254, DateTimeKind.Unspecified).AddTicks(6513),
                            PaymentStatus = 0,
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 2, 7, 6, 40, 46, 870, DateTimeKind.Unspecified).AddTicks(8577),
                            PaymentStatus = 0,
                            UserId = 1
========
                            Id = 4,
                            Date = new DateTime(2024, 6, 28, 13, 52, 12, 766, DateTimeKind.Unspecified).AddTicks(1256),
                            PaymentStatus = 0,
                            UserId = 3
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            BookId = 4,
========
                            BookId = 1,
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                            OrderId = 1,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            OrderId = 2,
                            Quantity = 3
========
                            OrderId = 1,
                            Quantity = 5
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            BookId = 4,
                            OrderId = 2,
========
                            BookId = 3,
                            OrderId = 1,
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                            Quantity = 5
                        },
                        new
                        {
                            Id = 4,
                            BookId = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            OrderId = 3,
                            Quantity = 5
========
                            OrderId = 2,
                            Quantity = 3
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 5,
                            BookId = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            OrderId = 4,
                            Quantity = 2
========
                            OrderId = 3,
                            Quantity = 1
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 6,
                            BookId = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            OrderId = 4,
                            Quantity = 4
========
                            OrderId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 7,
                            BookId = 2,
                            OrderId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 8,
                            BookId = 4,
                            OrderId = 4,
                            Quantity = 5
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Name = "Kuhn Inc"
========
                            Name = "Herzog Inc"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Name = "Rutherford and Sons"
========
                            Name = "Ernser - Tremblay"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Name = "O'Kon Inc"
========
                            Name = "Hermann LLC"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Name = "Will - Gislason"
========
                            Name = "Gerhold Inc"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Email = "Zander.Zemlak@gmail.com",
                            IsBanned = false,
                            Username = "Junius18"
========
                            Email = "Aiyana16@hotmail.com",
                            IsBanned = false,
                            Username = "Wilma75"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 2,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Email = "Lempi_Beer@yahoo.com",
                            IsBanned = false,
                            Username = "Arianna_Bartell"
========
                            Email = "Juliet_Bartell@hotmail.com",
                            IsBanned = true,
                            Username = "Michele.Block1"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 3,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Email = "Cydney71@yahoo.com",
                            IsBanned = false,
                            Username = "Era56"
========
                            Email = "Amalia_Streich3@gmail.com",
                            IsBanned = false,
                            Username = "Delaney.OConnell4"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 4,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Email = "Ethyl_Brown93@hotmail.com",
                            IsBanned = false,
                            Username = "Lenna.Ryan26"
========
                            Email = "Emmett26@hotmail.com",
                            IsBanned = false,
                            Username = "Colton.Brekke"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 5,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Email = "Tanner86@gmail.com",
                            IsBanned = false,
                            Username = "Margot_Monahan"
========
                            Email = "Carolanne_Bernhard@gmail.com",
                            IsBanned = false,
                            Username = "Darron.Bergnaum"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 6,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Email = "Emile25@gmail.com",
                            IsBanned = false,
                            Username = "Franz.Cassin"
========
                            Email = "Gunner_Kling@yahoo.com",
                            IsBanned = false,
                            Username = "Janick9"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 7,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Email = "Kieran56@yahoo.com",
                            IsBanned = false,
                            Username = "Leann11"
========
                            Email = "Verner_Hansen@hotmail.com",
                            IsBanned = false,
                            Username = "Maiya83"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        },
                        new
                        {
                            Id = 8,
<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
                            Email = "Oleta.Adams19@gmail.com",
                            IsBanned = false,
                            Username = "Eugenia57"
========
                            Email = "Polly_Klocko@gmail.com",
                            IsBanned = false,
                            Username = "Rosalee.Reilly69"
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                        });
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.HasOne("DAL.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "LastEditedBy")
                        .WithMany()
                        .HasForeignKey("LastEditedById");

                    b.HasOne("DAL.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("LastEditedBy");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("DAL.Models.BookReview", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.CartItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Cart")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
            modelBuilder.Entity("DAL.Models.GiftcardCode", b =>
                {
                    b.HasOne("DAL.Models.Giftcard", "Giftcard")
                        .WithMany("Codes")
                        .HasForeignKey("GiftcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Giftcard");

                    b.Navigation("Order");
========
            modelBuilder.Entity("DAL.Models.GenreBook", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany("Genres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                });

            modelBuilder.Entity("DAL.Models.LocalIdentityUser", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.HasOne("DAL.Models.GiftcardCode", "GiftcardCode")
                        .WithMany()
                        .HasForeignKey("GiftcardCodeId");

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiftcardCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.WishlistItem", b =>
                {
                    b.HasOne("DAL.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Models.LocalIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Models.LocalIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.LocalIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Models.LocalIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("Reviews");
                });

<<<<<<<< HEAD:DAL.WebAPI.Migrations/Migrations/20251129150137_AddGiftcardCodeToOrder.Designer.cs
            modelBuilder.Entity("DAL.Models.Giftcard", b =>
                {
                    b.Navigation("Codes");
========
            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Navigation("Books");
>>>>>>>> 2505e1e (updated genres in DAL):DAL.WebAPI.Migrations/Migrations/20251129094838_genre_book.Designer.cs
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DAL.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
